# HERENCIA: IMAGINA UN CLASE PADRE Y AHORA VA A EXISTIR UNA CLASE HIJA LA CUAL VA A HEREDAR ATRIBUTOS O METODOS DE LA CLASE PADRE
#           SE USA PARA ESTRUCTURAR LAS CLASES A NIVEL JERARQUICO, DONDE EXISTA UN PADRE Y MULTIPLES HIJOS, ESTO CON EL FIN DE REUTILIZAR CODIGO MAS EFICIENTE

# CREACION DE LA CLASE PADRE