# *ARGS: (*args), PERMITE QUE UNA FUNCION RECOPILE UN NUMERO VARIABLE DE ARGUMENTOS POSICIONALES EN UNA TUPLA PARA SU PROCESAMIENTO.

def suma(*args):       # ==> USANDO (*args), NOS SIRVE PARA QUE LA FUNCION ACEPTE n CANTIDAD DE PARAMETROS Y ASI QUITAR EL LIMITANTE
    total = sum(args)  #     ACA HACEMOS USO DE LA FUNCION "sum(x)", PARA PODER SUMAR LA n CANTIDAD DE PARAMATROS QUE EXISTAN.
    return total

operacion = suma(2, 3, 10, 3, 5, 6)       # ==> ACA SE PUEDE OBSERVAR COMO NO IMPORTA LA CANTIDAD DE PARAMETROS SIEMPRE LOS VA A SUMAR EN ESTE CASO
print(f"El resultado es {operacion}")

# COMO FUNCIONA (*args): LO QUE HACE ESTA FUNCION ES ACEPTAR MULTIPLES VALORES LOS CUALES LOS CONVIERTE EN TUPLA, PARA DESPUES USAR LA FUNCION SUMA Y ASI LOGRAR EL OBJETIVO DESEADO
