# BIENVENIDOS AL CURSO DE PROGRAMACION EN PYTHON CREADO POR MI CRISTHIAN CORTES ARIZA "SEVEM" LLAMADO DE "CERO A SEVEN",
# APRENDERAS DESDE LOS FUNDAMENTOS HASTA ASPECTOS MAS AVANZADOS, ESTE CURSO TIENE COMO FINALIDAD
# DEMOSTRAR LO QUE LLEVO APRENDIDO HASTA AHORA, COMO AUN SIGO EN FORMACION NO ESTA COMPLETO PERO SE IRA ACTUALIZANDO A MEDIDA DEL PASO DEL TIEMPO :D

# RECUERDA POR CADA PUNTO, QUE VEAS, LO PRACTIQUES LIBREMENTE CON CUALQUIER TIPO DE APLICACION QUE TE VENGA A LA CABEZA LA IDEA DE ESTE CURSO ES CULTIVAR UNA SEMILLA DE 
# LOGICA DE PROGRAMACION EN TI, ESPERO TE GUSTE Y APRECIES!



# PUEDES USAR EL EDITOR DE CODIGO QUE MAS TE GUSTE!