# PROGRAMACION ORIENTADA A OBJETOS: UNO DE LOS PARADIGMAS MAS IMPORTANTES DE LA PROGRAMACION


# 2 CONCEPTOS IMPORTANTES CLASES Y OBJETOS:

# CLASES: SON COMO ESTRUCTURAS BASICAS (PLANOS)
# OBJETOS: INSTANCIAS DE LA CLASE, ES DECIR, USA EL PLANO PERO ADICIONALMENTE LE AGREGA COSAS QUE LO HACEN DIFERENTES.

# LOS OBJETOS SE CONFORMAN DE ATRIBUTOS Y METODOS, ATRIBUTOS COMO CARACTERISTICAS Y METODOS COMO ACCIONES O COMPORTAMIENTO

# 4 PILARES: 1. ENCAPSULAMIENTO, 2. HERENCIA, 3. POLIMORFISMO, 4. ABSTRACCION
