# PROGRAMACION ORIENTADA A OBJETOS - CLASES Y OBJETOS:

# CLASES: APARTIR DE UNA CLASE SE PUEDEN CREAR MULTIPLES OBJETOS (UNA CLASE ES UN TIPO DE PLANTILLA O PROTOTIPO PARA CREAR OBJETOS. LOS OBJETOS SON INSTANCIAS ESPECIFICAS DE UNA CLASE)

# CREACION DE CLASE:
class Pikachu: # ==> DE ESTA FORMA SE DEFINE UNA CLASE PRIMERO LA PALABRA RESERVADA "class" Y DESPUES EL NOMBRE QUE SEA DESCRIPTIVO SU PRIMERA LETRA DEBE SER MAYUSCULA.
# EL PRIMER CONCEPTO DE UNA CLASE SON LOS ATRIBUTOS, EXISTEN DOS: 1. clase: SON COMPARTIDOS POR TODOS LOS OBJETOS CREADOS APARTIR DE ESA CLASE, TIPO UNA HERENCIA
#                                                                 2. instancia: SON VALORES PROPIOS DE CADA OBJETO
    tipo = "Electrico" # ==> ESTE ES UN ATRIBUTO DE CLASE, YA QUE ES UN ATRIBUTO QUE PERTENECE A TODOS LOS PIKACHUS EXISTENTES

    def __init__(self, nombre, nivel, sal): # ==> ASI SE DEFINEN LOS ATRIBUTOS DE INSTANCIA, SE USA LA PALABRA RESERVADA "def", SEGUIDO DE "__init__(x):", self NO ES PALABRA RESERVADA PERO POR CONVENSION SE USA
        self.nombre = nombre # ==> ASI ESTABLECEMOS VALORES DINAMICAMENTE.
        self.nivel = nivel  # ==>
        self.salud = sal # ==> TODAS ESTAS SON VARIABLES DE INSTANCIA ES DECIR SE PUEDEN VARIAR DEPENDIENDO QUE ESTABLEZCA CADA OBJETO

# CREACION DE OBJETOS EN BASE A ESA CLASE:
pikachu_1 = Pikachu("Pokachu", 750, 500) # ==> DE ESTA FORMA SE CREA UN OBJETO USANDO DE BASE UNA CLASE, EN ESTE CASO MI OBJETO ES "pikachu_1" Y CON EL IGUAL HAGO REFERENCIA A LA CLASE "Pikachu()"
print(pikachu_1.tipo)
print(pikachu_1.nombre)
print(pikachu_1.nivel)
print(pikachu_1.salud)

pikachu_2 = Pikachu("Pedro", 1000, 1000)
print(pikachu_2.tipo)
print(pikachu_2.nombre)
print(pikachu_2.nivel)
print(pikachu_2.salud)

# Y DE ESTA FORMA CREAMOS DIFERNTES OBJETOS EN BASE A UNA PLANTILLA (CLASE), GRACIAS A LAS VARIABLES DINAMICAS, ESO SI EL ATRIBUTO DE CLASE SE MANTIENE Y SE MANTENDRA
# EN TODOS LOS OBJETOS QUE CREEMOS A PARTIR DE ESA CLASE.