# FUNCIONES LAMBDA: ESTE ES OTRO TIPO DE FUNCION (FUNCIONES ANONIMAS), SON SIMPLES QUE SE UTILIZAN PARA REALIZAR OPERACIONES RAPIDAS Y PEQUEÑAS EN EXPRESIONES.
#                   SON UTILES EN SITUACIONES DONDE SE NECESITAN FUNCIONES TEMPORALES O FUNCIONES DE ORDEN SUPERIOR. SON MUY UTILIZADAS EN FUNCIONES DE ORDEN SUPERIOR

# CREAR FUNCION DE FORMA TRADICIONAL
def retornar_nota(estudiante): # ESTA FUNCION RECIBE DE PARAMETRO UN ESTUDIANTE Y AL SER UNA TUPLA ACCEDEMOS AL INDICE 1 MEDIANTE [1], PARA RETORNAR LA NOTA
    return estudiante[1]
# CREAR FUNCION CON LAMBDA:
# lambda estudiante: estudiante[1]  ==> ASPECTO DE MEJORA: CAMBIAR EL NOMBRE PARA QUE NO SEA TAN AUTODESCRIPTIVO, Y NO CAMBIARA NADA
# lambda x: x[1] ==> DE ESTA FORMA SERIA LA CORRECTA, POR CIERTO ESTA FUNCION SE ANONIMA SE ESCRIBE DENTRO DE LA FUNCION SORTED(), DE ESTA FORMA: 



# EJEMPLO PRACTICO: LISTA DE ESTUDIANTES CON NOMBRE Y NOTAS , ORDENARLOS EN BASE A ESAS NOTAS:
lista_estudiantes = [('Cristhian', 4.0),
                     ('Pepe', 2.5),
                     ('Maria', 3.1),         # ==> EN ESTE CASO YA QUE VAMOS A TRABAJAR CON DOS ELEMENTOS QUE NO TIENEN NADA EN COMUN (string e integer), ENTONCES USAREMOS UNA TUPLA
                     ('Carlos', 4.5)]       #     UNA LISTA PUEDE CONTENER UNA TUPLA DE ESTA FORMA.

# COMO VAMOS A ORDENAR ESA LISTA EN BASE A LAS NOTAS, TENDREMOS QUE USAR UNA FUNCION DE ORDEN SUPERIOR LA CUAL NOS ACEPTA; LOS DATOS CON LOS QUE TRABAJA Y UNA FUNCION COMO PARAMETRO
# LA FUNCION DE ORDEN SUPERIOR SE LLAMA "sorted(iterable, key=funcion(x))"
lista_ordenada = sorted(lista_estudiantes, key=retornar_nota, reverse=True) # ==> PARA QUE NOS RETORNE DE MAYOR A MENOS Y NO DE MENOR A MAYOR (ESTA PORDEFECTO), USAREMOS ", reverse=True"
print(lista_ordenada)



# LAMBDA: NO TIENE NOMBRE DE FUNCION EN LUGAR DE ESO VA EL ARGUMENTO DESPUES DE DOS PUNTOS DEFINIMOS EL CUERPO DE LA FUNCION (LA LOGICA), LAMBDA SIEMPRE HARA UN RETURN IMPLICITO

# lambda estudiante: estudiante[1]  ==> ASPECTO DE MEJORA: CAMBIAR EL NOMBRE PARA QUE NO SEA TAN AUTODESCRIPTIVO, Y NO CAMBIARA NADA
# lambda x: x[1] ==> DE ESTA FORMA SERIA LA CORRECTA, POR CIERTO ESTA FUNCION SE ANONIMA SE ESCRIBE DENTRO DE LA FUNCION SORTED(), DE ESTA FORMA:

lista_ordenada = sorted(lista_estudiantes, key=lambda estudiante:estudiante[1], reverse=True) # ==> DE ESTA FORMA EL CODIGO SE VUELVE MAS COMPACTO, SE CREAN FUNCIONES SIMPLES Y CORTAS
print(lista_ordenada)                                                                         #     PARA EVITAR LA CREACION DE UNA FUNCION QUE SE USARA UNA VEZ