# FUNCIONES LAMBDA:

# PRACTICA PARA ENTENDERLA MEJOR:

lista = [1, 2, 3]

retorno = lambda x:x[1] # ==> ESTA FUNCION NECESITA COMO ARGUMENTO EN SU PRIMERA X UN ITERABLE(LISTA, TUPLA, DICCIONARIO, ETC...) Y EN EL SEGUNDO ES LO QUE NOS RETORNARA EN ESTE CASO LO QUE EXISTA EN EL INDICE 1
# ==> AL GUARDAR UNA FUNCION LAMBDA EN UNA VARIABLE PODRAS MANTENERLA Y USARLA EN OTROS LADOS DEL CODIGO(NO TIENE SENTIDO YA QUE LAS FUNCIONES LAMBDA
#     SUELEN SER MUY ESPECIFICAS Y CORTAS, PODRIA NO APLICAR PARA OTRO LADO, PERO BUENO SE PUEDE HACER Xd)
print(retorno(lista))


# EJERCICIO PRACTICO: CREAR UNA LAMBDA FUNCTION QUE TOME DOS ARGUMENTOS COMO ENTRADA Y RETORNE LA SUMA DE ESOS DOS:

# lista1 = [1, 2]
# suma = lambda x:x+x
# print(suma(lista1))
              # ==> EN ESTA PARTE SE USA x Y y, PORQUE SON VARIABLES NO IMPORTA EL NOMBRE EN REALIDAD Y EN ESTA PRIMERA PARTE DE LA FUNCION LAMBDA (ANTES DE LOS DOS PUNTOS), 
              #     SE PONEN LA CANTIDAD DE ARGUMENTOS QUE RECIBIRA LA FUNCION Y DESPUES DE LOS DOS PUNTOS SE HARA LA OPERACION CORRESPONDE
sumar = lambda x, y : x + y # ==> EL RETORNO IMPLICITO 
print(sumar(5, 15))

restar = lambda num1, num2 : num1 - num2
print(restar(25, 5))

multiplicar = lambda num1, num2 : num1 * num2
print(multiplicar(5, 4))

dividir = lambda num1, num2 : num1 / num2
print(dividir(100, 5))